server:
  port: 8080

spring:
  application:
    name: project_data
  datasource:
    # 数据库连接URL优化
    url: jdbc:mysql://localhost:3306/project_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接池配置 - 使用HikariCP（Spring Boot 2.x 默认）
    hikari:
      # 连接池中允许的最小连接数
      minimum-idle: 5
      # 连接池中允许的最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时时间(毫秒)
      connection-timeout: 30000
      # 连接空闲超时时间(毫秒)
      idle-timeout: 600000
      # 连接最大存活时间(毫秒)
      max-lifetime: 1800000
      # 连接池名称
      pool-name: ProjectDataHikariCP
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
      # 连接初始化SQL
      connection-init-sql: SET NAMES utf8mb4
      # 验证连接的超时时间
      validation-timeout: 3000
      # 是否在连接池中维护空闲连接
      leak-detection-threshold: 60000

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.xiaobai.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 全局配置
  global-config:
    db-config:
      # 主键类型
      id-type: AUTO
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 关闭banner
    banner: false
  # 配置